fix-up so it actually works

diff --git a/bin/php-fcgi b/bin/php-fcgi
--- a/bin/php-fcgi
+++ b/bin/php-fcgi
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! /bin/bash
 ### BEGIN INIT INFO
 # Provides:          php-fcgi
 # Required-Start:    $remote_fs
@@ -17,58 +17,41 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="PHP FCGI Spawner"
 NAME=php-fcgi
-DAEMON=/usr/bin/php-cgi
+DAEMON=/usr/bin/php5-cgi
 BIND=127.0.0.1:9000
 USER=nginxd
-CHILDREN=15
-MAXREQS=1000
+PHP_FCGI_CHILDREN=15
+PHP_FCGI_MAXREQS=1000
+PHP_CGI=${DAEMON}
+PHP_CGI_NAME=`basename ${PHP_CGI}`
+PHP_CGI_ARGS="- USER=$USER PATH=/usr/bin PHP_FCGI_CHILDREN=$PHP_FCGI_CHILDREN PHP_FCGI_MAX_REQUESTS=$PHP_FCGI_MAX_REQUESTS $PHP_CGI -b $BIND"
+RETVAL=0
 CONFIG=/etc/nginx/fastcgi.conf
-DAEMON_ARGS="- USER=${USER} PHP_FCGI_CHILDREN=${CHILDREN} PHP_FCGI_MAX_REQUESTS=${MAXREQS} ${DAEMON} -b ${BIND}"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
-
-# Read configuration variable file if it is present
-[ -r ${CONFIG} ] && . ${CONFIG}
+if [ ! -x ${DAEMON} ] ; then
+	echo "Daemon ($DAEMON) is not Executable"
+	exit 0
+fi 
 
 # Load the VERBOSE setting and other rcS variables
-. /lib/init/vars.sh
+. /lib/init/vars.sh || echo "failed with VERBOSE"
 
 # Define LSB log_* functions.
 # Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
-. /lib/lsb/init-functions
+. /lib/lsb/init-functions || echo "lsb FAIL"
 
-#
-# Function that starts the daemon/service
-#
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid ${USER} --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid ${USER} --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+	echo -n "Starting $DESC"
+       	start-stop-daemon --start --quiet --pidfile $PIDFILE --background --start --chuid ${USER} --exec /usr/bin/env -- $PHP_CGI_ARGS \
+               	|| return 0
 }
-
-#
-# Function that stops the daemon/service
-#
+ 
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
 	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
@@ -78,6 +61,7 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
+	echo "Still stopping $DAEMON ... please to be waiting"
 	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
@@ -115,15 +99,6 @@ case "$1" in
 		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
-  #reload|force-reload)
-	#
-	# If do_reload() is not implemented then leave this commented out
-	# and leave 'force-reload' as an alias for 'restart'.
-	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
   restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
@@ -147,7 +122,6 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
 	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
 	exit 3
 	;;
